import types from 'redux-types';

export default types('patient', [
  'SET_PATIENT_STORE',
  'CLEAR_PATIENT_STORE',
  'SET_PATIENT_STORE_UPDATING',
  'UPDATE_ACTIVE_VISITS_IN_STORE',
  'ADD_PATIENT_TO_STORE',
  'UPDATE_PATIENT_IN_STORE',
  'SET_SELECTED_PATIENT',
  'CLEAR_SELECTED_PATIENT'
] );
