export const UPDATE_SERVICEWORKER = 'UPDATE_SERVICEWORKER'

export default {
  SYSTEM_POLL_START: 'SYSTEM_POLL_START',
  SYSTEM_POLL_STOP: 'SYSTEM_POLL_STOP',
  SYSTEM_POLL_SUCCESS: 'SYSTEM_POLL_SUCCESS',
  SYSTEM_POLL_FAILURE: 'SYSTEM_POLL_FAILURE',
};
